# Generated by Django 4.2.7 on 2023-12-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kipapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='section',
            new_name='state',
        ),
    ]
