# Generated by Django 4.2.7 on 2023-12-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipapp', '0002_rename_section_userprofile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='passout_year',
            field=models.CharField(max_length=20),
        ),
    ]
